### PR TITLE
Feature/actions feedback

### PR DESCRIPTION
**Pull request by Alexerson**
Adding more JS notifications and card visual movements for actions

### CODE REVIEW

**Comment by Alexerson** [comment]
I moved all the actionResolve state functions to a single module as well. 

Because the history was weird (you could see the effect of the card before knowing the user played the card), I had to switch the card movement and the card application. 
This means some resolution will have to change (I think about "empty the trash" so far, but maybe others will show up).

Also, I'm proposing a new solution for the action resolution, i.e. adding a "interactionNeeded" value, that will help the JS know what it should enable (hand selection, keeper selection, player selection, etc.). 
This means a bit more code, but in the end it's easier to work with I think.

Otherwise it's going well, I'll keep adding Action feedback this week.

**Comment by Alexerson** [comment]
By the way, I suggest you merge the PR in order, otherwise the diff won't necessary make sense.

**Comment by Alexerson** [comment]
I thought this would be merged into develop but was only merged into the other branch. I've merged everything into develop. You should probably pull from develop again locally. @tomlowi

**Comment by tomlowi** [comment]
Allright, I've been checking and testing a little bit, nice work.
Wondering what I can do with the limited time I have this week, maybe a
small isolated task I can do is to refactor the card-definitions to all
come from te factories?
That doesn't interfer at all with everything else going on.
I will setup a (limited) KeeperFactory then and remove the material
definitions.

Unless you think of something else?

**Comment by Alexerson** [comment]
I think it's a brilliant idea, yes!
I'll keep going through the Action you already implemented and add the notifications on my side.
I'll probably stay away from the "hard" actions (the one needing a new state) and will focus on the "free action" rules if I have time.

**Pull request merged**
