### PR TITLE
Feature/wolmot

### PR DESCRIPTION
**Pull request by tomlowi**
animate actions + hand/keeper limits + installed and ran prettier with default setup

### CODE REVIEW

**Comment by Alexerson** [comment]
I've done some work FE side to split the code in modules. Do you mind looking at my 2 PRs? I'll backport your changes to it after that if needed and will merge this.

**Comment by Alexerson** [comment]
For prettier, this should do. I'll add some Github actions as well so we don't have to worry to much about styling.

**Comment by tomlowi** [comment]
Hi Alex,

I have approved and merged your PRs, but I am now faced with the fact that
your changes seem to conflict with the changes I did to make the keeper
limit and hand limit states multi-player (because all players can do
this simultaneously).

This worked fine in my branch, but now I get errors in your keepersLimit.js
, I see notifications like "you must remove X Keepers for Keeper Limit -1"
and js errors for "During notification gameStateChange
Cannot read property 'setSelectionMode' of undefined"

I suppose because in onEnteringStateKeepersLimit you are using things like

stock[this.player_id].setSelectionMode(2);

And this.player_id is probably not defined in multiplayer states...

We will have to look further into this to get everything working cleanly
again.

I have another branch prepared for the handling of the Goals cards and
cleanly checking win conditions etc, but we will first have to get
this figured out.

Op zo 27 dec. 2020 om 16:59 schreef Alexerson <notifications@github.com>:

**Comment by tomlowi** [comment]
Ah,

it is somewhat different apparently, *this.player_id* is always defined but
the check for isCurrentPlayerActive can not be used in multiplayer states:

https://boardgamearena.com/doc/Game_interface_logic:_yourgamename.js#Notifications
*Warning*: for multipleactiveplayer states: the active players are NOT
actives yet so you must use onUpdateActionButtons to perform the client
side operation which depends on a player active/unactive status. If you are
doing initialization of some structure which do not depend on active
player, you can just replace

 if (this.isCurrentPlayerActive()) {

into

 if (!this.isSpectator) {

for the main switch in that method.


So I think in the OnUpdateActionButtions in main .js and
in onEnteringStateKeepersLimit / onEnteringStateHandLimit you should use
!isSpectator instead of isCurrentPlayerActive .

And also there is a bug in the keepersLimit.js, using

stock[this.player_id].setSelectionMode(2);

 is invalid because "stock" is already setup
as this.keepersStock[this.player_id], so the extra  stock[this.player_id]
is too much.

I am going to quit for today, I will check tomorrow if you had time to fix
it or otherwise I will try to make PR for it myself.

Grtz,

Iwan



Op zo 27 dec. 2020 om 20:12 schreef Iwan Tomlow <iwan.tomlow@gmail.com>:

**Comment by tomlowi** [comment]
I think we best just discard this branch

**Comment by Alexerson** [comment]
I was trying to merge it at the moment, but most of it was done indeed.

**Pull request closed without merging**
