### PR TITLE
Feature/wolmot carddefinitions

### PR DESCRIPTION
**Pull request by tomlowi**
hi Alex, I think this should do the trick for the card definitions.
Good thing also is that this forces all Cards files to be loaded on game start, so it actually detected some merge issues (duplicate brackets) in ActionStealAKeeper etc even if you never played that card.

Side effect is that the tooltips for some Rule cards will show "Not Implemented" instead of the actual text, but that will be solved as soon as we have those cards setup.
I will do that next (without implementation), because now we have lost those descriptions for the moment.

### CODE REVIEW

**Comment by Alexerson** [comment]
Great, I see the new rules definitions, so merging!
I'll try to spend some time today to make sure the game is playable, because at the moment, if you play an action that is not implemented, you are stuck, so we can show some stuff to Looney Labs.
If I have more than a bit of time, I'll actually implement some of them (keeper selection, rules selection, keeper exchange, etc.)

**Comment by tomlowi** [comment]
Yes, that would be great, if the not yet implemented actions would default
back to a “Do It” button that doesn’t have any effect yet.
I think we have something that can be private alfa then indeed.

Some other things I was thinking about and we should discuss and agree
further:

- I noticed you changed the behaviour of some Actions (like Zap a Card) to
resolve immediately when the card is selected.
For some cards that might be ok, but when player needs to select multiple I
think for sure we need a “Confirm” button.
And then I would prefer to have this consistent for all resolve actions,
also to prevent people coming to complain and ask for an Undo system
because they misclicked (I generally prefer to avoid Undo at all if
possible)

- for all Rules that take instant effect like the Double Agenda or the
Inflation, there are 2 roads to choose from, like we already discussed for
the Draw/Play rules also:
 - either check the rules in play every time to “calculate” each time, like
you have done now for the Double Agenda.
In this case the implementation in the Cards itself would actually do
nothing
 - or we define extra game states for these cards (“hasDoubleAgenda”,
“hasInflation”) , and we set / unset these game states when those rule
cards are played/discarded

Personally I prefer option 2, as it will make checking and usings those
things in all other actions and rules much easier and more clear (and
probably more performant).
If we go for option 1 , I think at least we should add utility functions to
check if those rules are active, because your Double Agenda check is now
already there in 2 places with the hard coded card Id . E.g. Inflation will
have to be checked and applied in a multitude of actions and rules.

Best regards

Op donderdag 7 januari 2021 schreef Alexerson <notifications@github.com>:

**Comment by Alexerson** [comment]
Hey,

I actually took the time to read before bed 😃

For the card selection, I thought BGA was recommending to avoid asking confirmation multiple times if not needed. For actions that are about selecting just one card, that's why I removed the confirmation. I agree that we shouldn't support info in this game. But I'm not 100% Sure what's best. Removing the confirmation makes the dev faster because I don't have to click multiple times before seeing my debug messages, but we can totally put it back.  We can also ask BGA/Looney what they prefer.

For the double agenda (And inflation, but empty hand bonus as well I think and maybe others), you are right that the current situation is not correct. On a purely theorical standpoint, I prefer option 1 with utility functions. But on a practical level, option 2 might be easier and maybe slightly more performant so let's go for this one.

**Comment by tomlowi** [comment]
Yes, games should try to avoid useless confirmation, but even if you have
to select only 1 card players can still mis-click or change their mind.
So I think in this case confirmation is useful.
If you look at Bang now for instance, if you need to select 1 card from
Storehouse for instance, they also let you select and confirm.

It's different if you have buttons already to choose left/right or
rock/paper/scissors: you don't want another confirm button after that.
But for all card selection, I think it would be best.

Agreed for the rules, we'll set it up like this then.

Goodnight!

**Pull request merged**
